name: "Pull Target Files from Applanga"
on: workflow_dispatch
jobs:
  pull-translation-in:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          path: 'checkout'
      - uses: applanga/setup-applanga-cli@v1.0.1
        with:
          version: 1.0.48
      - name: Pull translations from Applanga
        env: 
         APPLANGA_ACCESS_TOKEN: 62e80d5c70978e744412a4a6!7965ba4766b5ff2999156b6ae7d0403a
        run: applanga pull
        working-directory: checkout
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: newTranslations
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          commit-message: Updated translations
          title: Updated translations 
          body: Pulled in new translations from Applanga portal
          path: 'checkout'
