name: "Push Source Files to Applanga"
on:
 push:
   branches:
     - main
   paths:
     - react_json_sample/en/*.json
   
jobs:
  push-sources-for-translation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'checkout'
      - uses: applanga/setup-applanga-cli@v1.0.1
        with:
          version: 1.0.48
      - name: Push Sources to Applanga
        env: 
         APPLANGA_ACCESS_TOKEN: 62e80d5c70978e744412a4a6!7965ba4766b5ff2999156b6ae7d0403a
        run: applanga push --force
        working-directory: checkout
        
